### ISSUE TITLE
503 when upload new proposal

### ISSUE THREAD

**Issue by twodam** [jigglyjams/nance-ts#9] opened 2022-09-28 11:39 UTC
<img width="707" alt="image" src="https://user-images.githubusercontent.com/103885077/192769533-6d08121b-2285-498f-af30-a0f54629a48a.png">

Proposal with type other than `Payout` will get 503 response from API

**Comment by jigglyjams** [comment] 2022-09-28 23:04
Caused by 
https://github.com/jigglyjams/nance-ts/blob/55d8d2db4bbe83c08ca39708f602bdcf57c8f5a7/src/api/api.ts#L40
Trying to get `type` on `payout` when it doesnt exist

**Comment by jigglyjams** [comment] 2022-09-28 23:15
Need to add a column to proposal database for reserve payout percentage

**Comment by jigglyjams** [comment] 2022-09-29 06:11
Should be fixed by https://github.com/jigglyjams/nance-ts/blob/eba16d76a3a648a3e63b097e3ddf2349deb7198b/src/api/api.ts#L40

**Closed by jigglyjams** 2022-09-29 06:11 UTC
Labels: bug
